---

image: "nexus.fillswim.local:8086/docker.elastic.co/beats/filebeat"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

daemonset:
  extraEnvs:
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: password

  # # Allows you to add any config files in /usr/share/filebeat
  # # such as filebeat.yml for daemonset
  # filebeatConfig:
  #   filebeat.yml: |
  #     filebeat.inputs:
  #     - type: container
  #       paths:
  #         - /var/log/containers/*.log
  #       processors:
  #       - add_kubernetes_metadata:
  #           host: ${NODE_NAME}
  #           matchers:
  #           - logs_path:
  #               logs_path: "/var/log/containers/"

  #     output.elasticsearch:
  #       host: '${NODE_NAME}'
  #       hosts: '["https://${ELASTICSEARCH_HOSTS:elasticsearch-master.elk.svc.cluster.local:9200}"]'
  #       username: '${ELASTICSEARCH_USERNAME}'
  #       password: '${ELASTICSEARCH_PASSWORD}'
  #       protocol: https
  #       ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca.crt"]