image:
  repository: grafana/mimir
  tag: 3.0.0

global:

  extraEnvFrom:
    - secretRef:
        name: minio-for-mimir-secret

  dnsService: kube-dns
  dnsNamespace: kube-system
  clusterDomain: cluster.local.

ingress:
  enabled: false
# ingress:
#   enabled: true
#   ingressClassName: "nginx"
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: ca-cluster-issuer
#   hosts:
#     - mimir.fillswim.local
#   tls:
#     - secretName: mimir-distribted-tls
#       hosts:
#         - mimir.fillswim.local

mimir:

  structuredConfig:

    common:
      storage:
        backend: s3
        s3:
          endpoint: minio.minio.svc.cluster.local:9000
          access_key_id: ${MINIO_ACCESS_KEY}
          secret_access_key: ${MINIO_SECRET_KEY}
          insecure: true
          http:
            insecure_skip_verify: true

    limits:
      ingestion_rate: 200000
      ingestion_burst_size: 500000
      max_global_series_per_user: 1500000

    ingest_storage:
      enabled: false
    ingester:
      push_grpc_method_enabled: true

    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-blocks

    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: mimir-alertmanager

    ruler_storage:
      backend: s3
      s3:
        bucket_name: mimir-ruler

    memberlist:
      join_members:
        - mimir-gossip-ring.mimir.svc.cluster.local:7946
      cluster_label: "mimir-main"

ingester:
  enabled: true
  replicas: 3
  persistentVolume:
    enabled: true
    name: storage
    accessModes:
      - ReadWriteOnce
    size: 20Gi

store_gateway:
  enabled: true
  replicas: 3
  persistentVolume:
    enabled: true
    name: storage
    accessModes:
      - ReadWriteOnce
    size: 20Gi

distributor:
  enabled: true
  replicas: 3

querier:
  enabled: true
  replicas: 3

query_frontend:
  replicas: 3

query_scheduler:
  replicas: 3

ruler:
  replicas: 3

alertmanager:
  replicas: 3

compactor:
  replicas: 3
  # persistentVolume:
  #   size: 10Gi

gateway:

  replicas: 3

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: ca-cluster-issuer
      # Рекомендуемые настройки для Mimir Gateway
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    hosts:
      # --- Основной домен ---
      - host: mimir.fillswim.local
        paths:
          - path: /
            pathType: Prefix
      # --- Домены для Alertmanager ---
      - host: mimir-alertmanager-dev.fillswim.local
        paths:
          - path: /
            pathType: Prefix
      - host: mimir-alertmanager-stage.fillswim.local
        paths:
          - path: /
            pathType: Prefix
      - host: mimir-alertmanager-fillswim.fillswim.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mimir-alertmanager-tls
        hosts:
          - mimir.fillswim.local
          - mimir-alertmanager-dev.fillswim.local
          - mimir-alertmanager-stage.fillswim.local
          - mimir-alertmanager-fillswim.fillswim.local

  nginx:
    config:
      file: |
        worker_processes  5;  ## Default: 1
        error_log  /dev/stderr {{ .Values.gateway.nginx.config.errorLogLevel }};
        pid        /tmp/nginx.pid;
        worker_rlimit_nofile 8192;

        events {
          worker_connections  4096;  ## Default: 1024
        }

        http {
          client_body_temp_path /tmp/client_temp;
          proxy_temp_path       /tmp/proxy_temp_path;
          fastcgi_temp_path     /tmp/fastcgi_temp;
          uwsgi_temp_path       /tmp/uwsgi_temp;
          scgi_temp_path        /tmp/scgi_temp;

          default_type application/octet-stream;
          log_format   {{ .Values.gateway.nginx.config.logFormat }}

          {{- if .Values.gateway.nginx.verboseLogging }}
          access_log   /dev/stderr  main;
          {{- else }}

          map $status $loggable {
            ~^[23]  0;
            default 1;
          }
          access_log   {{ .Values.gateway.nginx.config.accessLogEnabled | ternary "/dev/stderr  main  if=$loggable;" "off;" }}
          {{- end }}

          sendfile           on;
          tcp_nopush         on;
          proxy_http_version 1.1;

          {{- if .Values.gateway.nginx.config.resolver }}
          resolver {{ .Values.gateway.nginx.config.resolver }};
          {{- else }}
          resolver {{ .Values.global.dnsService }}.{{ .Values.global.dnsNamespace }}.svc.{{ .Values.global.clusterDomain }};
          {{- end }}

          {{- with .Values.gateway.nginx.config.httpSnippet }}
          {{ . | nindent 2 }}
          {{- end }}

          # # Ensure that X-Scope-OrgID is always present, default to the no_auth_tenant for backwards compatibility when multi-tenancy was turned off.
          # map $http_x_scope_orgid $ensured_x_scope_orgid {
          #   default $http_x_scope_orgid;
          #   "" "{{ include "mimir.noAuthTenant" . }}";
          # }

          # ========================================================
          #                 CUSTOM TENANT LOGIC
          # ========================================================
          map $http_host $tenant_by_host {
            hostnames;
            mimir.fillswim.local                   "{{ include "mimir.noAuthTenant" . }}";
            mimir-alertmanager-dev.fillswim.local       dev;
            mimir-alertmanager-stage.fillswim.local     stage;
            mimir-alertmanager-fillswim.fillswim.local  fillswim;
            default                                 "{{ include "mimir.noAuthTenant" . }}";
          }

          map $http_x_scope_orgid $ensured_x_scope_orgid {
            default $http_x_scope_orgid;
            ""      $tenant_by_host;
          }
          # ========================================================

          map $http_x_scope_orgid $has_multiple_orgid_headers {
            default 0;
            "~^.+,.+$" 1;
          }

          proxy_read_timeout 300;
          server {
            listen {{ include "mimir.serverHttpListenPort" . }};

            # ====================================================================
            # Указываем ваши домены здесь (необязательно, но полезно для порядка)
            # ====================================================================
            server_name mimir-alertmanager-dev.fillswim.local mimir-alertmanager-stage.fillswim.local mimir-alertmanager-fillswim.fillswim.local;
            # ====================================================================

            {{- if .Values.gateway.nginx.config.enableIPv6 }}
            listen [::]:{{ include "mimir.serverHttpListenPort" . }};
            {{- end }}

            {{- if .Values.gateway.nginx.config.clientMaxBodySize }}
            client_max_body_size {{ .Values.gateway.nginx.config.clientMaxBodySize }};
            {{- end }}

            {{- if .Values.gateway.nginx.basicAuth.enabled }}
            auth_basic           "Mimir";
            auth_basic_user_file /etc/nginx/secrets/.htpasswd;
            {{- end }}

            if ($has_multiple_orgid_headers = 1) {
                return 400 'Sending multiple X-Scope-OrgID headers is not allowed. Use a single header with | as separator instead.';
            }

            location = / {
              return 200 'OK';
              auth_basic off;
            }

            location = /ready {
              return 200 'OK';
              auth_basic off;
            }

            proxy_set_header X-Scope-OrgID $ensured_x_scope_orgid;

            # Distributor endpoints
            location /distributor {
              set $distributor {{ template "mimir.fullname" . }}-distributor-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$distributor:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }
            location = /api/v1/push {
              set $distributor {{ template "mimir.fullname" . }}-distributor-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$distributor:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }
            location /otlp/v1/metrics {
              set $distributor {{ template "mimir.fullname" . }}-distributor-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$distributor:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }

            # Alertmanager endpoints
            location {{ template "mimir.alertmanagerHttpPrefix" . }} {
              set $alertmanager {{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$alertmanager:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }
            location = /multitenant_alertmanager/status {
              set $alertmanager {{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$alertmanager:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }
            location = /multitenant_alertmanager/configs {
              set $alertmanager {{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$alertmanager:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }
            location = /api/v1/alerts {
              set $alertmanager {{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$alertmanager:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }

            # Ruler endpoints
            location {{ template "mimir.prometheusHttpPrefix" . }}/config/v1/rules {
              set $ruler {{ template "mimir.fullname" . }}-ruler.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$ruler:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }
            location {{ template "mimir.prometheusHttpPrefix" . }}/api/v1/rules {
              set $ruler {{ template "mimir.fullname" . }}-ruler.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$ruler:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }

            location {{ template "mimir.prometheusHttpPrefix" . }}/api/v1/alerts {
              set $ruler {{ template "mimir.fullname" . }}-ruler.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$ruler:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }
            location = /ruler/ring {
              set $ruler {{ template "mimir.fullname" . }}-ruler.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$ruler:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }

            # Rest of {{ template "mimir.prometheusHttpPrefix" . }} goes to the query frontend
            location {{ template "mimir.prometheusHttpPrefix" . }} {
              set $query_frontend {{ template "mimir.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$query_frontend:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }

            # Buildinfo endpoint can go to any component
            location = /api/v1/status/buildinfo {
              set $query_frontend {{ template "mimir.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$query_frontend:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }

            # Compactor endpoint for uploading blocks
            location /api/v1/upload/block/ {
              set $compactor {{ template "mimir.fullname" . }}-compactor.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass      http://$compactor:{{ include "mimir.serverHttpListenPort" . }}$request_uri;
            }

            {{- with .Values.gateway.nginx.config.serverSnippet }}
            {{ . | nindent 4 }}
            {{- end }}
          }
        }

minio:
  enabled: false

kafka:
  enabled: false
