apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply -f K8s1-RHEL/additions/rabbitmq/VSO-RabbitMQ-VaultStaticSecret.yaml
# kubectl delete -f K8s1-RHEL/additions/rabbitmq/VSO-RabbitMQ-VaultStaticSecret.yaml

kind: VaultStaticSecret
metadata:
  name: rabbitmq-vault-static-secret
  namespace: rabbitmq
spec:
  vaultAuthRef: rabbitmq-static-auth
  mount: rabbitmq                      # Папка с секретами в Vault (Vault -> "Secrets Engines")
  type: kv-v2
  path: rabbitmq-secret                # Путь к секрету в папке из пункта "mount"
  refreshAfter: 10s                    # Интервал обновления секрета
  destination:
    create: true                       # Создать секрет, если его нет
    name: rabbitmq-my-secret           # Имя секрета
  # rolloutRestartTargets:
  # - kind: StatefulSet                  # Какой ресурс надо перезапустить
  #   name: rabbitmq                     # Имя ресурса
