apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply -f /root/Vault-Secrets-Operator/Grafana/Grafana-VaultAuth.yaml
# kubectl delete -f /root/Vault-Secrets-Operator/Grafana/Grafana-VaultAuth.yaml

kind: VaultAuth
metadata:
  name: grafana-static-auth
  namespace: grafana
spec:
  # vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: grafana-ui-secret-role
    serviceAccount: default
    audiences:
      - vault