apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply -f Vault-Secrets-Operator/Grafana/Grafana-VaultStaticSecret.yaml
# kubectl delete -f Vault-Secrets-Operator/Grafana/Grafana-VaultStaticSecret.yaml

kind: VaultStaticSecret
metadata:
  name: grafana-vault-static-secret-ui
  namespace: grafana
spec:
  vaultAuthRef: grafana-static-auth
  # mount: kv-v2
  mount: grafana
  type: kv-v2
  # path: grafana/grafana-ui          # Путь к секрету
  path: grafana-ui-secret           # Путь к секрету
  refreshAfter: 10s                 # Интервал обновления секрета
  destination:
    create: true                    # Создать секрет, если его нет
    name: grafana-my-secret         # Имя секрета
  rolloutRestartTargets:
  - kind: Deployment                # Какой ресурс надо перезапустить
    name: grafana                   # Имя ресурса
