apiVersion: argoproj.io/v1alpha1
kind: Application

# kubectl apply -f my-tomcat-ArgoCD-App.yaml
# kubectl delete -f my-tomcat-ArgoCD-App.yaml

metadata:
  name: my-tomcat-app                                    # Название создаваемого Argo CD application
  namespace: argo-cd                                    # namespace, в котором будет создаваться Argo CD application
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:

  project: default

  destination:
    name: in-cluster                                    # Деплой в этот же кластер
    namespace: my-tomcat                                 # В какой namespace будет производиться деплой

  sources:
  - repoURL: 'https://fillswim.github.io/HelmChats'     # Репозиторий с Helm чартом
    # path: "My-Template-HelmChart/"
    chart: my-template-helmchart                        # Наименование Helm чарта
    targetRevision: 0.0.8                               # Версия Helm чарта
    helm:
      # releaseName: my-tomcat-argocd-deploy               # Название релиза
      # parameters:
      # # Образ
      # - name: "container.image"
      #   value: "tomcat:8.5.38"
      #   forceString: true
      # # Порт на контейнере
      # - name: "containerPort"
      #   value: "8080"
      # # Порт на сервисе
      # - name: "servicePort"
      #   value: "8081"
      # # Ограничение по CPU
      # - name: "cpuUtilization"
      #   value: "50"
      # # Ограничение по памяти
      # - name: "memoryUtilization"
      #   value: "80"
      # # Адрес публикации
      # - name: "host"
      #   value: "tomcat.fillswim.local"
      #   forceString: true
      # # Класс Ingress контроллера
      # - name: "ingressClassName"
      #   value: "nginx"
      #   forceString: true
      valueFiles:
      - $values/Helm-values/my-tomcat-values.yaml
  - repoURL: 'https://github.com/fillswim/ArgoCD.git'   # Репозиторий с values
    targetRevision: main
    ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
