apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply  -f K8s1-RHEL/additions/loki/VSO-Loki-MinIO-VaultStaticSecret.yaml
# kubectl delete -f K8s1-RHEL/additions/loki/VSO-Loki-MinIO-VaultStaticSecret.yaml

kind: VaultStaticSecret
metadata:
  name: minio-for-loki-vault-static-secret
  namespace: loki
spec:
  vaultAuthRef: loki-static-auth
  mount: minio                      # Папка с секретами в Vault (Vault -> "Secrets Engines")
  type: kv-v2
  path: minio-secret                # Путь к секрету в папке из пункта "mount"
  refreshAfter: 10s                 # Интервал обновления секрета
  destination:
    create: true                    # Создать секрет, если его нет
    name: minio-for-loki-secret # Имя секрета
  rolloutRestartTargets:
  - kind: StatefulSet               # Какой ресурс надо перезапустить
    name: loki-compactor            # Имя ресурса
  - kind: StatefulSet
    name: loki-ingester-zone-a
  - kind: StatefulSet
    name: loki-ingester-zone-b
  - kind: StatefulSet
    name: loki-ingester-zone-c
