hostname: rancher-alma-k8s2.fillswim.local

bootstrapPassword: "password"

service:
  type: ""
  annotations: {}
  # An optional security setting to disables the HTTP port of the rancher service
  # When set true, you must also set `ingress.servicePort` to 443 and the appropriate ingress annotation to use HTTPS
  disableHTTP: false

ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  extraAnnotations: {}
  ingressClassName: nginx
  # Certain ingress controllers will require the pathType or path to be set to a different value.
  pathType: ImplementationSpecific
  path: "/"
  # Backend port number; should use either: 80, or 443.
  # Must use 443 when `service.disableHTTP` is set to true.
  servicePort: 80

  # configurationSnippet - Add additional Nginx configuration. This example statically sets a header on the ingress.
  # configurationSnippet: |
  #   more_set_input_headers "X-Forwarded-Host: {{ .Values.hostname }}";

  tls:
    # options: rancher, letsEncrypt, secret
    source: secret
    secretName: rancher-tls