apiVersion: argoproj.io/v1alpha1
kind: Application

# http://gifservice.fillswim.local/swagger-ui/index.html

# kubectl apply -f K8s1-RHEL/applications-non-sync/gifservice.yaml
# kubectl delete -f K8s1-RHEL/applications-non-sync/gifservice.yaml

metadata:
  name: gifservice                                                                  # Название создаваемого Argo CD application
  namespace: argo-cd                                                                # namespace, в котором будет создаваться Argo CD application
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    name: in-cluster                                                                # Деплой в этот же кластер
    namespace: gifservice                                                           # В какой namespace будет производиться деплой

  sources:
    - repoURL: "https://fillswim.github.io/HelmChats/"                              # Репозиторий с Helm чартом
    # - repoURL: "http://nexus.fillswim.local:8081/repository/helm-hosted/"           # Репозиторий с Helm чартом
    # - repoURL: "https://charts.bitnami.com/bitnami"                                 # Репозиторий с Helm чартом
      chart: my-template-helmchart                                                  # Наименование Helm чарта
      targetRevision: 0.0.9                                                         # Версия Helm чарта
      helm:
        releaseName: gifservice                                                     # Название релиза

        # Values относительно репозитория
        valueFiles:
          - $values/K8s1-RHEL/helm-values/gifservice-values-2025-01-10.yaml

    # Репозиторий с values
    - repoURL: "https://github.com/fillswim/ArgoCD.git"
      targetRevision: main
      ref: values

    # Дополнительная папка для отслеживания
    - repoURL: 'https://github.com/fillswim/ArgoCD.git'
      path: "K8s1-RHEL/additions/gifservice"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - RespectIgnoreDifferences=true
      # - ServerSideApply=true