apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply -f K8s1-RHEL/additions/rabbitmq-apps/VSO-RabbitMQ-Apps-VaultAuth.yaml
# kubectl delete -f K8s1-RHEL/additions/rabbitmq-apps/VSO-RabbitMQ-Apps-VaultAuth.yaml

kind: VaultAuth
metadata:
  name: rabbitmq-static-auth
  namespace: rabbitmq-apps
spec:
  # vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: rabbitmq-secret-role
    serviceAccount: default
    audiences:
      - vault