apiVersion: argoproj.io/v1alpha1
kind: Application

# kubectl apply  -f K8s1-RHEL/applications-non-sync/rhel-k8s1/postgresql-cnpg-gitlab.yaml
# kubectl delete -f K8s1-RHEL/applications-non-sync/rhel-k8s1/postgresql-cnpg-gitlab.yaml

metadata:
  name: postgresql-cnpg-gitlab-rhel-k8s1                                            # Название создаваемого Argo CD application
  namespace: argo-cd                                                                # namespace, в котором будет создаваться Argo CD application
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background

spec:
  project: default

  destination:
    name: in-cluster                                                                # Деплой в этот же кластер
    namespace: cnpg-system                                                          # В какой namespace будет производиться деплой

  sources:
    - repoURL: "https://cloudnative-pg.github.io/charts"                            # Репозиторий с Helm чартом
      chart: cloudnative-pg                                                         # Наименование Helm чарта
      targetRevision: 0.26.1                                                        # Версия Helm чарта
      helm:
        releaseName: cloudnativepg                                                  # Название релиза

    # Дополнительная папка для отслеживания
    - repoURL: 'https://github.com/fillswim/ArgoCD.git'
      path: "K8s1-RHEL/additions/additions-rhel-k8s1/postgresql-cnpg-gitlab"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - RespectIgnoreDifferences=true
      # - ServerSideApply=true