apiVersion: external-secrets.io/v1beta1

# kubectl apply -f External-Secrets-Operator/ExternalSecret.yaml
# kubectl delete -f External-Secrets-Operator/ExternalSecret.yaml

kind: ExternalSecret
metadata:
  name: vault-externalsecret-grafana
  namespace: grafana
spec:
  refreshInterval: "15s"
  secretStoreRef:                       # Ссылка на SecretStore для Vault
    name: vault-clustersecretstore
    kind: ClusterSecretStore
  target:                               # Какой секрет должен быть создан
    name: grafana-my-secret
  data:                                 # Откуда нужно получить секрет
  - secretKey: admin-user
    remoteRef:
      key: grafana-ui-secret
      property: admin-user

  - secretKey: admin-password
    remoteRef:
      key: grafana-ui-secret
      property: admin-password
