apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply  -f K8s1-RHEL/additions/minio/VSO-MinIO-VaultStaticSecret.yaml
# kubectl delete -f K8s1-RHEL/additions/minio/VSO-MinIO-VaultStaticSecret.yaml

kind: VaultStaticSecret
metadata:
  name: minio-vault-static-secret
  namespace: minio
spec:
  vaultAuthRef: minio-static-auth
  mount: minio                      # Папка с секретами в Vault (Vault -> "Secrets Engines")
  type: kv-v2
  path: minio-secret                # Путь к секрету в папке из пункта "mount"
  refreshAfter: 10s                 # Интервал обновления секрета
  destination:
    create: true                    # Создать секрет, если его нет
    name: minio-my-k8s-secret       # Имя секрета
  rolloutRestartTargets:
  - kind: StatefulSet               # Какой ресурс надо перезапустить
    name: minio                     # Имя ресурса
