apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply  -f K8s1-RHEL/additions/minio/VSO-MinIO-VaultAuth.yaml
# kubectl delete -f K8s1-RHEL/additions/minio/VSO-MinIO-VaultAuth.yaml

kind: VaultAuth
metadata:
  name: minio-static-auth
  namespace: minio
spec:
  # vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: minio-secret-role
    serviceAccount: default
    audiences:
      - vault