---

# Disable it to use your own elastic-credential Secret.
secret:
  enabled: true
  password: "elastic" # generated randomly if not defined

# image: "docker.elastic.co/elasticsearch/elasticsearch"
image: "nexus.fillswim.local:8086/docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi

# # Enabling this will publicly expose your Elasticsearch instance.
# # Only enable this if you have security enabled on your cluster
# ingress:
#   enabled: true
#   annotations: {}
#   kubernetes.io/ingress.class: nginx
#   # kubernetes.io/tls-acme: "true"
#   # className: "nginx"
#   pathtype: ImplementationSpecific
#   hosts:
#     - host: elastic.fillswim.local
#       paths:
#         - path: /
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local