deploymentMode: Distributed

loki:
  # -- Storage config. Providing this will automatically populate all necessary storage configs in the templated config.
  storage:
    # Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
    # Please provide these values if you are using object storage.
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      s3: http://api.minio.fillswim.local
      endpoint: http://api.minio.fillswim.local
      # region: null
      secretAccessKey: "Hiwk-dJFj-bRbB-i65r"
      accessKeyId: "minioadmin"
      # signatureVersion: null
      s3ForcePathStyle: true
      insecure: true
      http_config: {}
      # -- Check https://grafana.com/docs/loki/latest/configure/#s3_storage_config for more info on how to provide a backoff_config
      backoff_config: {}
      disable_dualstack: false

  useTestSchema: false

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
