## RabbitMQ Authentication parameters
##
auth:

  username: user
  # password: "password"

  ## @param auth.existingPasswordSecret Existing secret with RabbitMQ credentials (existing secret must contain a value for `rabbitmq-password` key or override with setting auth.existingSecretPasswordKey)
  ## e.g:
  ## existingPasswordSecret: name-of-existing-secret
  ##
  existingPasswordSecret: "rabbitmq-my-secret"
  ## @param auth.existingSecretPasswordKey [default: rabbitmq-password] Password key to be retrieved from existing secret
  ## NOTE: ignored unless `auth.existingSecret` parameter is set
  ##
  existingSecretPasswordKey: "rabbitmq-password"

  erlangCookie: "rD2r5ZJh952Vqond"

replicaCount: 3

# service:
#   # type: ClusterIP
#   type: LoadBalancer
#   loadBalancerIP: "192.168.2.228"

ingress:
  enabled: true
  hostname: rabbitmq.fillswim.local
  ingressClassName: "nginx"