## RabbitMQ Authentication parameters
##
auth:
  username: user
  password: "password"
  securePassword: true
  updatePassword: false
  existingPasswordSecret: ""
  existingSecretPasswordKey: ""
  enableLoopbackUser: false
  erlangCookie: "rD2r5ZJh952Vqond"
  existingErlangSecret: ""
  existingSecretErlangKey: ""

replicaCount: 1

service:
  # type: ClusterIP
  type: LoadBalancer
  loadBalancerIP: "192.168.2.228"

ingress:
  enabled: false
  hostname: rabbitmq.fillswim.local
  ingressClassName: "nginx"