## RabbitMQ Authentication parameters
##
auth:
  username: user
  password: "password"
  securePassword: true
  updatePassword: false
  existingPasswordSecret: ""
  existingSecretPasswordKey: ""
  enableLoopbackUser: false
  erlangCookie: "rD2r5ZJh952Vqond"
  existingErlangSecret: ""
  existingSecretErlangKey: ""

replicaCount: 1

service:
  # type: ClusterIP
  type: LoadBalancer
  loadBalancerClass: "nginx"
  # loadBalancerIP: "192.168.2.228"
  externalIPs:
    - 192.168.2.228

ingress:
  enabled: false
  path: /
  pathType: ImplementationSpecific
  hostname: rabbitmq.local
  ingressClassName: ""