apiVersion: secrets.hashicorp.com/v1beta1

# kubectl apply  -f K8s1-RHEL/additions/grafana/VSO-Grafana-VaultAuth.yaml
# kubectl delete -f K8s1-RHEL/additions/grafana/VSO-Grafana-VaultAuth.yaml

kind: VaultAuth
metadata:
  name: grafana-static-auth
  namespace: grafana
spec:
  # vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: grafana-ui-secret-role
    serviceAccount: default
    audiences:
      - vault