---
apiVersion: v1
kind: Service

# kubectl apply -f Redis/redis-service-lb.yaml
# kubectl delete -f Redis/redis-service-lb.yaml

metadata:
  name: redis-service-lb                      # Имя сервиса
  namespace: redis 

spec:
  type: LoadBalancer                # Тип сервиса
  loadBalancerIP: 192.168.2.227     # По какому адресу будет доступно приложение (http://192.168.2.227:6379)
  selector:
    app.kubernetes.io/name: redis   #! На поды с какими лейблами будет работать сервис, распространять трафик
  ports:
  - port: 6379                      # Какой на Load Balancer будет открыть порт
    targetPort: 6379                #!! Порт на поде