apiVersion: argoproj.io/v1alpha1
kind: Application

# kubectl apply -f root-ArgoCD-App.yaml
# kubectl delete -f root-ArgoCD-App.yaml

metadata:
  name: root-app                                        # Название создаваемого Argo CD application
  namespace: argo-cd                                    # namespace, в котором будет создаваться Argo CD application
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:

  project: default

  destination:
    name: in-cluster                                    # Деплой в этот же кластер
    namespace: argo-cd                                  # В какой namespace будет производиться деплой

  sources:
  - repoURL: 'https://github.com/fillswim/ArgoCD.git'   # Репозиторий с Helm чартом
    path: "applications"                                # Относительный путь отслеживаемой папки
    targetRevision: HEAD                                # Версия Helm чарта

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
