---
apiVersion: v1

# kubectl apply  -f  k8s-manifests/grafana/grafana-secret.yaml
# kubectl delete -f  k8s-manifests/grafana/grafana-secret.yaml

kind: Secret
metadata:
  name: grafana-secret
  namespace: grafana
type: Opaque
stringData:
  admin-user: admin
  admin-password: password