apiVersion: argoproj.io/v1alpha1
kind: Application

# kubectl apply  -f K8s1-RHEL/applications-non-sync/alma-k8s2/alloy-alma-k8s2.yaml
# kubectl delete -f K8s1-RHEL/applications-non-sync/alma-k8s2/alloy-alma-k8s2.yaml

metadata:
  name: alloy-alma-k8s2                                                       # Название создаваемого Argo CD application
  namespace: argo-cd                                                          # namespace, в котором будет создаваться Argo CD application
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background

spec:
  project: default

  destination:
    name: kubernetes-admin-alma-k8s2@alma-k8s2                                # Деплой в этот же кластер
    namespace: alloy                                                          # В какой namespace будет производиться деплой

  sources:

    - repoURL: "https://grafana.github.io/helm-charts"                        # Репозиторий с Helm чартом
      chart: alloy                                                            # Наименование Helm чарта
      targetRevision: 1.5.2                                                   # Версия Helm чарта
      helm:
        releaseName: alloy                                                    # Название релиза
        valueFiles:
          # - $values/K8s1-RHEL/helm-values/alma-k8s2/alloy/alloy-values-1.5.2.yaml
          - $values/alloy-values-1.5.2.yaml

    - repoURL: "https://github.com/fillswim/ArgoCD.git"                       # Репозиторий с values
      targetRevision: main
      ref: values
      path: "K8s1-RHEL/helm-values/alma-k8s2/alloy"
      kustomize: {}

    - repoURL: 'https://github.com/fillswim/ArgoCD.git'                       # Репозиторий
      path: "K8s1-RHEL/additions/additions-alma-k8s2/alloy"                   # Относительный путь отслеживаемой папки
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      # - ServerSideApply=true