apiVersion: argoproj.io/v1alpha1
kind: Application

# kubectl apply -f K8s1-RHEL/applications/hashicorp-vault.yaml
# kubectl delete -f K8s1-RHEL/applications/hashicorp-vault.yaml

metadata:
  name: vault # Название создаваемого Argo CD application
  namespace: argo-cd # namespace, в котором будет создаваться Argo CD application
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    name: in-cluster # Деплой в этот же кластер
    namespace: vault # В какой namespace будет производиться деплой

  sources:
    - repoURL: "http://nexus.fillswim.local:8081/repository/helm-hosted/" # Репозиторий с Helm чартом
      chart: vault # Наименование Helm чарта
      targetRevision: 0.30.0 # Версия Helm чарта
      helm:
        releaseName: vault # Название релиза
        valueFiles:
          - $values/K8s1-RHEL/helm-values/hashicorp-vault-ha-raft-without-tls.yaml
    - repoURL: "https://github.com/fillswim/ArgoCD.git" # Репозиторий с values
      targetRevision: main
      ref: values

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
