apiVersion: argoproj.io/v1alpha1
kind: Application

# kubectl apply -f K8s1-RHEL/applications-non-sync/vault-secrets-operator.yaml
# kubectl delete -f K8s1-RHEL/applications-non-sync/vault-secrets-operator.yaml

metadata:
  name: vault-secrets-operator                                                            # Название создаваемого Argo CD application
  namespace: argo-cd                                                        # namespace, в котором будет создаваться Argo CD application
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  destination:
    name: in-cluster                                                        # Деплой в этот же кластер
    namespace: vault-secrets-operator-system                                # В какой namespace будет производиться деплой

  sources:
    - repoURL: "http://nexus.fillswim.local:8081/repository/helm-hosted/"   # Репозиторий с Helm чартом
      chart: vault-secrets-operator                                                 # Наименование Helm чарта
      targetRevision: 0.9.0                                                         # Версия Helm чарта
      helm:
        releaseName: vault-secrets-operator                                         # Название релиза

        # Values относительно репозитория
        valueFiles:
          - $values/K8s1-RHEL/helm-values/vso-values-2024-11-24.yaml

        # # Переопределенный параметр в values
        # parameters:
        # - name: "preUpgradeChecker.jobEnabled"
        #   value: "false"

    # Репозиторий с values
    - repoURL: "https://github.com/fillswim/ArgoCD.git"
      targetRevision: main
      ref: values

     # Дополнительная папка для отслеживания
    - repoURL: 'https://github.com/fillswim/ArgoCD.git'
      path: "K8s1-RHEL/additions/vault-secrets-operator"
      targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - RespectIgnoreDifferences=true
      # - ServerSideApply=true