apiVersion: external-secrets.io/v1beta1

# kubectl apply -f External-Secrets-Operator/ClusterSecretStore.yaml
# kubectl delete -f External-Secrets-Operator/ClusterSecretStore.yaml

kind: ClusterSecretStore
metadata:
  name: vault-clustersecretstore
  namespace: default
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"     # Адрес сервера Vault
      path: "grafana"                                         # Путь к папке с секретами в Vault
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:                                       # В каком секрете хранится root токен от Vault  
          name: "vault-token"
          key: "token"
          namespace: default